name: test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: false
      - run: |
          which slangroom-exec
          slangroom-exec --version
          which slexfe
          slexfe --version
          make check
